name: Building and Testing

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libgtest-dev libsqlite3-dev cmake build-essential
          git clone https://github.com/SRombauts/SQLiteCpp.git
          cd SQLiteCpp && mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install


      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run test start
        run: |
          cd build/app
          ./test_start

      - name: Run tests
        run: |
          cd build/test
          ./note_test
          ./db_test